eth:
  - cables_1
  - cables_2
  - cables_3
  - camera_shake_1
  - camera_shake_2
  - camera_shake_3
  - ceiling_1
  - ceiling_2
  - desk_3
  - desk_changing_1
  - einstein_1
  - einstein_2
  - einstein_flashlight
  - einstein_global_light_changes_1
  - einstein_global_light_changes_2
  - einstein_global_light_changes_3
  - kidnap_1
  - large_loop_1
  - mannequin_1
  - mannequin_3
  - mannequin_4
  - mannequin_5
  - mannequin_7
  - mannequin_face_1
  - mannequin_face_2
  - mannequin_face_3
  - mannequin_head
  - motion_1
  - planar_2
  - planar_3
  - plant_1
  - plant_2
  - plant_3
  - plant_4
  - plant_5
  - plant_scene_1
  - plant_scene_2
  - plant_scene_3
  - reflective_1
  - repetitive
  - sfm_bench
  - sfm_garden
  - sfm_house_loop
  - sfm_lab_room_1
  - sfm_lab_room_2
  - sofa_1
  - sofa_2
  - sofa_3
  - sofa_4
  - sofa_shake
  - table_3
  - table_4
  - table_7
  - vicon_light_1
  - vicon_light_2  
  - boxes
  - buddha
  - cables_4
  - cables_5
  - desk_1
  - desk_2
  - desk_changing_2
  - desk_global_light_changes
  - desk_ir_light
  - dino
  - drone
  - foreground_occlusion
  - helmet
  - kidnap_2
  - lamp
  - large_loop_2
  - large_loop_3
  - large_non_loop
  - motion_2
  - motion_3
  - motion_4
  - planar_1
  - reflective_2
  - scale_change
  - table_1
  - table_2
  - table_5
  - table_6
  - table_global_light_changes
  - table_local_light_changes
  - table_scene